Tools qa
Elici965/cypress-workshop pull request #13
Opened 2022-03-16 19:36 UTC by Elici965

2022-03-17 13:54 UTC, salorrego requested changes

2022-03-17 13:54 UTC, salorrego commented on cypress/integration/locators.spec.ts
> +      it('when the user fills the form',() => {
what should be the then here?

2022-03-17 13:54 UTC, salorrego commented on cypress/integration/locators.spec.ts
> +      it('when the user fills the form',() => {
what are you validating?

2022-03-22 21:25 UTC, Elici965 commented on cypress/integration/locators.spec.ts
> +      it('when the user fills the form',() => {
Changes were uploaded.

2022-03-22 23:06 UTC, salorrego requested changes

2022-03-22 23:06 UTC, salorrego commented on cypress/integration/locators.spec.ts
> +  })
```suggestion
    it('then the information should be submited.',() =>
    {
      personalInformation.test();
    })
  })
```
anything else that tells us that the test is successful?

2022-03-22 23:06 UTC, salorrego commented on cypress/page/personal-information.page.ts
> +  public test() {
maybe a better name for this, something like `checkIfFormIsSubmited` or `expectFormSubmited`

2022-03-30 15:00 UTC, closed without merging