files page object Model
Elici965/cypress-workshop pull request #8
Opened 2022-01-12 22:06 UTC by Elici965

2022-01-12 22:16 UTC, salorrego approved these changes

2022-01-12 22:26 UTC, salorrego requested changes

2022-01-12 22:26 UTC, salorrego commented on cypress/integration/buy-tshirt.spec.ts
> +import { OrderSummary } from '../page';
junta todos los import en uno solo

2022-01-12 23:09 UTC, Elici965 commented on cypress/integration/buy-tshirt.spec.ts
> +import { OrderSummary } from '../page';
Actualizados a una sola línea

2022-01-13 14:19 UTC, salorrego requested changes

2022-01-13 14:19 UTC, salorrego commented on cypress/integration/buy-tshirt.spec.ts
> +import { MenuContentPage,ProductListPage,ProductAddedModal, SummaryPage,SignInPage, AddressPage, ShippingPage, PaymentPage, BankPaymentPage, OrderSummary } from '../page';
esta linea esta demasiado larga, cambiala asi para que se pueda leer facil:
```suggestion
import { 
  MenuContentPage,
  ProductListPage,
  ProductAddedModal, 
  SummaryPage,
  SignInPage, 
  AddressPage, 
  ShippingPage, 
  PaymentPage, 
  BankPaymentPage, 
  OrderSummary
} from '../page';
```

2022-01-13 14:27 UTC, salorrego approved these changes
awesome

2022-01-13 14:31 UTC, merged